### ISSUE TITLE
Latex not installed error

### ISSUE THREAD

**Issue by Fortuntato** [saigkill/latex_curriculum_vitae-dotnet#8]
**Describe the bug**
When running the project for the first time, if the user does not have Latex already installed in the machine, the automatic installation of it presents an error.

**To Reproduce**
Run the project without having Latex installed

**Expected behavior**
The program should lead to the URL of the page where to download Latex to be used in the software

**Screenshots or error pop up**
![image](https://user-images.githubusercontent.com/37523381/97038667-113ba800-1563-11eb-8f56-3355089f1c9e.png)

**Environment tested**
- OS: Windows 10
- Version Visual Studio 2019 used: 16.6.3

**Additional context**
- The exception comes up when the code goes to Setup.cs (line 60) in CheckLatePath()
- The Error message is "Could not find a part of the path 'C:\texlive'."

**Comment by saigkill** [comment]
Hi @Fortuntato,
can you try to try it again in the develop branch? I added the special System.IO.DirectoryNotFoundException to the try catch range. [https://github.com/saigkill/latex_curriculum_vitae-dotnet/blob/develop/latex_curriculum_vitae/Setup.cs](https://github.com/saigkill/latex_curriculum_vitae-dotnet/blob/develop/latex_curriculum_vitae/Setup.cs)

**Comment by Fortuntato** [comment]
I can't find a way to update my upstream (of my fork repository) from you 'develop' branch.
Can you please update the code change into your master branch? I saw the new if statement, should be fine. There is just an empty line that you should probably delete

**Comment by saigkill** [comment]
@Fortuntato : I merged all stuff to the master branch. So you should work with him now.

**Comment by Fortuntato** [comment]
Hey, I am still getting errors... I think I will install the latex version manually for now. I think an easy solution would be to just prompt a window saying "Latex not found. Please ensure it is installed and available at C:\\texlive"

**Comment by saigkill** [comment]
@Fortuntato : I tried another way to launch the url ([https://stackoverflow.com/a/43232486](https://stackoverflow.com/a/43232486)). This one works for me. If you want, you can try it out. :-)

**Comment by Fortuntato** [comment]
Nice one, now the url launch works fine

**Comment by Fortuntato** [comment]
Woah! I did not know it would have taken so much time to install TexLive (full package). Would the user actually need to install everything or there are some packages we can avoid to install in order to use this software?

**Comment by saigkill** [comment]
> Woah! I did not know it would have taken so much time to install TexLive (full package). Would the user actually need to install everything or there are some packages we can avoid to install in order to use this software?

Yes Texlive is a big system. But in that case it gives the user ALL possible options to write their stuff. My delivered example just needs a few packages. But maybe the user wants to build it in another way.

I'm closing that issue for now, because that open issue is gone now.
